#%RAML 1.0
title: testing-mock

/users:
  get:
    responses:
      200:
        body:
          application/json:
            type: 

/user/{userId}:
  uriParameters:
    
  get:
    responses:
      200:
        body:
          application/json:
            type:
            
        
    